@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

HIDE_STEREOTYPE()

title Code diagram for Queries Component - API Application

Boundary(queries, "Queries Component") {
    interface IRequest
    interface IRequestHandler

    namespace WeatherForecast {

        class GetAllWeatherForcastQuery implements .IRequest

        class GetAllWeatherForcastQueryHandler implements .IRequestHandler {
            -_context
            +Handle()
        }

        class WeatherForecastDto {
            +Id
            +Date
            +TemperatureC
            +TemperatureF
            +Summary
        }

        Lay_U(WeatherForecastDto, GetAllWeatherForcastQuery)
    }
}

@enduml