@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

HIDE_STEREOTYPE()

title Code diagram for Infrastructure Data Component - API Application

Boundary(queries, "Infrastructure Data Component") {
    namespace Application {
        
        interface IApiDbContext {
            WeatherForcasts
            SaveChangesAsync()
        }
    }

    namespace Common.EF {
        
        abstract class BaseDbContext {
            #_currentUserService

            -Audit()
            -Concurrency()

            +SaveChanges()
            +SaveChangesAsync()
        }

        abstract class BaseTransactionalDbContext extends BaseDbContext implements ITransactionalDbContext

        interface ITransactionalDbContext {
            HasActiveTransaction

            CreateExecutionStrategy()
            GetCurrentTransaction()
            BeginTransactionAsync()
            CommitTranasctionAsync()
            RollbackTransaction()
        }
        class Extensions {
            {static} +UpdateManyToMany()
            {static} +MigrateDbContext()
        }
    }

    namespace Data {
        class ApiDbContext extends Common.EF.BaseTransactionalDbContext implements Application.IApiDbContext
        class WeatherForcastEntityTypeConfiguration {
            +Configure()
        }
    }
}

@enduml