@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

HIDE_STEREOTYPE()

title Code diagram for Commands Component - API Application

Boundary(commands, "Commands Component") {
    namespace Common.MediatR {
        interface IRequest
        interface IRequestHandler
        interface ITransactionalRequest
        class RequestResult
    }

    namespace WeatherForecast {

        class CreateWeatherForcastCommand implements Common.MediatR.IRequest, Common.MediatR.ITransactionalRequest {
            +Date
            +TemperatureC
            +Summary
        }

        class CreateWeatherForcastCommandHandler implements Common.MediatR.IRequestHandler {
            - _repository
            + Handle()
        }

        class DeleteWeatherForcastCommand implements Common.MediatR.IRequest, Common.MediatR.ITransactionalRequest {
            +Id
        }

        class DeleteWeatherForcastCommandHandler implements Common.MediatR.IRequestHandler {
            -_repository
            +Handle()
        }

        class CreateWeatherForcastValidator
        class DeleteWeatherForcastValidator

        Lay_U(CreateWeatherForcastCommandHandler, CreateWeatherForcastCommand)
        Lay_U(CreateWeatherForcastValidator,CreateWeatherForcastCommandHandler)

        Lay_U(DeleteWeatherForcastCommandHandler, DeleteWeatherForcastCommand)
        Lay_U(DeleteWeatherForcastValidator,DeleteWeatherForcastCommandHandler)
    }

    namespace Domain {
        interface IRepository<T> {
            Add()
            Remove()
            GetAsync()
            SaveChangesAsync()
        }

        interface IWeatherForecastRepository implements IRepository
    }
}

@enduml