@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

HIDE_STEREOTYPE()

title Code diagram for Policy Operations Component - Autorization Service

Boundary(policy_ops, "Policy Operations Component") {

    namespace Client {
        interface IPolicyOperations {
            EvaluateAsync(user)
            HasPermissionAsync(user, permission)
            IsInGroupAsync(user, group)
        }

        class PolicyOperations implements IPolicyOperations {
            -_policy
            +Constructor(policy)
        }
    }

    namespace Runtime {
        interface IPolicyCacher {
            GetPolicyAsync()
            ClearCachedPolicy()
        }

        class PolicyCacher implements IPolicyCacher {
            -_policyReader
            -_cache
        }

        class Policy {
            +UserGroups
            +Permissions
            EvaluateAsync(user)
        }
    }

    namespace Store {
        interface IPolicyReader {
            ReadPolicyAsync()
        }

        class PolicyReader implements IPolicyReader {
            -_policy
        }
    }
}

@enduml