@startuml

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

HIDE_STEREOTYPE()

title Component diagram for Weather Forecast System - Web Application

Person(user, "User", "The end user of the system.")

Container(spa, "Single-Page App", "Typescript, Angular", "Provides all the WFS functionality to users via their web browser")
Container(api, "API Application", "C#, ASP.NET Core Minimal Api", "Provides WFS functionality via API")
Container(authz, "Authorization Service", "ASP.NET Core Minimal Api", "Provides permission authorizations to the API service")

System_Ext(identity, "Duende IdentityServer", "User Auhentication and Token Issuer")
System_Ext(loki, "Grafana Loki", "Log aggregation system to store and query logs")

Container_Boundary(web_app, "Web Application") {
    Component(log, "Logging Middleware", "Serilog Logging", "Structured logging for all requests using Serilog.")
    Component(auth_mid, "Force Authentication Middleware", "ASP.NET Core Middleware", "Verify all requests are on behalf of an authenticated user.")
    Component(file, "File Fallback", "ASP.NET Core Endpoint", "Dilever the SPA App if no other path matches.")
    Component(auth, "OpenId Connect Middleware", "ASP.NET Core Middleware", "Provide OpenID Connect and OAuth 2.0 services.")
    Component(yarp, "YARP Reverse Proxy", "", "Proxy all traffic from the SPA to the API application.")
    Component(account_ep, "Account Endpoints", "ASP.NET Core Minimal Api", "Provide session and account endpoints")
}

Rel_Neighbor(user, log, "Request", "HTTPS")
Rel_L(user, spa, "Uses")
Rel(user, identity, "Authenticate", "HTTPS")
Rel_Neighbor(auth, identity, "Request Token")
Rel_U(file, spa, "Delivers")
Rel(spa, log, "Api Request", "JSON/HTTPS")
Rel(auth_mid, yarp, "/api")
Rel_U(auth_mid, file, "all other paths")
Rel_Neighbor(auth_mid, account_ep, "/account")
Rel(auth_mid, auth, "Unauthenticated")
Rel(yarp, api, "Proxy", "JSON/HTTPS")
Rel_R(api, authz, "Authorize", "JSON/HTTPS")
Rel_U(api, identity, "Validate Token", "HTTPS")
Rel_U(authz, identity, "Validate Token", "HTTPS")
Rel(log, auth_mid, "Forward Request")

Rel(log, loki, "Send Logs", "HTTPS")

Lay_R(auth, yarp)
Lay_L(user, spa)

@enduml