@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

HIDE_STEREOTYPE()

title Code diagram for MediatR Pipeline

Boundary(mediatr, "MediatR") {
    Boundary(behaviors, "Behaviors") {
             class EFTransactionBehavior {
            -_httpContextAccessor
            -_logger
            +Handle()
        }
        class LoggingBehavior {
            -_httpContextAccessor
            -_logger
            +Handle()
        }
        class ValidatorBehavior {
            -_validators
            -_logger
            +Handle()
        }
    }
    
    Boundary(interfaces, "Interfaces") {
        interface ISecuritySensitive {
            GetSafeCopy()
        }
        interface ITransactionalRequest
        interface IRequest<T>
        interface IRquestHandler<TRequest, TResponse> {
            TResponse Handle()
        }
    }

    class Extensions {
        {static} +AddMediatRServices()
    }
}

Lay_L(IRquestHandler, IRequest)
Lay_U(IRequest, ITransactionalRequest)
Lay_U(Extensions, IRequest)

@enduml