version: '3.9'

services:
  nginx-proxy:
    ports:
      - "8090:8090"
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/server.crt:/etc/nginx/conf/server.crt
      - ./certs/server.key:/etc/nginx/conf/server.key
    networks:
      - ca
    restart: always

  loki:
    expose:
      - "3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - ca
    restart: always

  prometheus:
    expose:
      - "9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    networks:
      - ca
    restart: always

  grafana:
    expose:
      - "3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - ca
    restart: always

  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ExternalAddress=https://${EXTERNAL_HOST_NAME}:8090
      - ClientUri=https://${EXTERNAL_HOST_NAME}:8080
      - Serilog__Loki__Enable=true
      - Serilog__Loki__Address=http://loki:3100
    volumes:
      - identity-dpk:/home/wfs/.aspnet/DataProtection-Keys
    expose:
      - "80"
    networks:
      - ca
    restart: always
  
  authorization:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - TokenAuthority=http://identity
      - Serilog__Loki__Enable=true
      - Serilog__Loki__Address=http://loki:3100
    expose:
      - "80"
    networks:
      - ca
    restart: always

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - TokenAuthority=http://identity
      - AuthorizationService=http://authorization
      - Serilog__Loki__Enable=true
      - Serilog__Loki__Address=http://loki:3100
    expose:
      - "80"
    networks:
      - ca
    restart: always

  bff:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - TokenAuthority=https://${EXTERNAL_HOST_NAME}:8090
      - ReverseProxy__Clusters__apicluster__Destinations__api1__Address=http://api
      - Serilog__Loki__Enable=true
      - Serilog__Loki__Address=http://loki:3100
    volumes:
      - bff-dpk:/home/wfs/.aspnet/DataProtection-Keys
    expose:
      - "80"
    networks:
      - ca
    restart: always
    extra_hosts:
      - "${EXTERNAL_HOST_NAME}:host-gateway"

networks:
  ca:

volumes:
  identity-dpk:
  bff-dpk:
  loki:
  grafana:
  prometheus:
