version: '3.9'

services:
  nginx-proxy:
    ports:
      - "8090:8090"
      - "8080:8080"
      - "3000:3000"
      - "15672:15672"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/server.crt:/etc/nginx/conf/server.crt
      - ./certs/server.key:/etc/nginx/conf/server.key
    networks:
      - ca

  loki:
    expose:
      - "3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
      - loki:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - ca

  prometheus:
    expose:
      - "9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus:/prometheus
    networks:
      - ca

  grafana:
    expose:
      - "3000"
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - ca

  rabbitmq:
    environment:
      - RABBITMQ_DEFAULT_USER=ca
      - RABBITMQ_DEFAULT_PASS=rabbitsecret
      - RABBITMQ_DEFAULT_VHOST=ca
    expose:
      - "5672"
      - "15672"
    volumes:
      - rabbit:/var/lib/rabbitmq/
    networks:
      - ca

  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ExternalAddress=https://${EXTERNAL_HOST_NAME}:8090
      - ClientUri=https://${EXTERNAL_HOST_NAME}:8080
      - Serilog__Loki__Enable=true
      - Serilog__Loki__Address=http://loki:3100
      - MassTransit__Enable=true
      - MassTransit__Host=rabbitmq
      - MassTransit__VHost=ca
      - MassTransit__Username=ca
      - MassTransit__Password=rabbitsecret
    volumes:
      - identity-dpk:/home/wfs/.aspnet/DataProtection-Keys
    expose:
      - "80"
    networks:
      - ca
  
  authorization:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - TokenAuthority=http://identity
      - Serilog__Loki__Enable=true
      - Serilog__Loki__Address=http://loki:3100
    expose:
      - "80"
    networks:
      - ca

  audit:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - TokenAuthority=http://identity
      - AuthorizationService=http://authorization
      - Serilog__Loki__Enable=true
      - Serilog__Loki__Address=http://loki:3100
      - MassTransit__Enable=true
      - MassTransit__Host=rabbitmq
      - MassTransit__VHost=ca
      - MassTransit__Username=ca
      - MassTransit__Password=rabbitsecret
    expose:
      - "80"
    networks:
      - ca

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - TokenAuthority=http://identity
      - AuthorizationService=http://authorization
      - Serilog__Loki__Enable=true
      - Serilog__Loki__Address=http://loki:3100
      - MassTransit__Enable=true
      - MassTransit__Host=rabbitmq
      - MassTransit__VHost=ca
      - MassTransit__Username=ca
      - MassTransit__Password=rabbitsecret
    expose:
      - "80"
    networks:
      - ca

  bff:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - TokenAuthority=https://${EXTERNAL_HOST_NAME}:8090
      - ReverseProxy__Clusters__apicluster__Destinations__api1__Address=http://api
      - ReverseProxy__Clusters__auditcluster__Destinations__audit1__Address=http://audit
      - Serilog__Loki__Enable=true
      - Serilog__Loki__Address=http://loki:3100
    volumes:
      - bff-dpk:/home/wfs/.aspnet/DataProtection-Keys
    expose:
      - "80"
    networks:
      - ca
    extra_hosts:
      - "${EXTERNAL_HOST_NAME}:host-gateway"

networks:
  ca:

volumes:
  identity-dpk:
  bff-dpk:
  loki:
  grafana:
  prometheus:
  rabbit:
