version: '3.9'

services:
  nginx-proxy:
    image: nginx:alpine
    depends_on:
      - identity
      - bff
      - grafana

  loki:
    image: grafana/loki:2.5.0

  prometheus:
    image: prom/prometheus
    
  grafana:
    image: grafana/grafana:latest

  rabbitmq:
    image: rabbitmq:3-management-alpine

  identity:
    image: ca/identity
    build:
      context: ../.
      dockerfile: src/CA.Identity/Dockerfile
    depends_on:
      - loki

  authorization:
    image: ca/authorization
    build:
      context: ../.
      dockerfile: src/CA.Authorization/Dockerfile
    depends_on:
      - identity
      - loki

  audit:
    image: ca/audit
    build:
      context: ../.
      dockerfile: src/CA.Audit/Dockerfile
    depends_on:
      - identity
      - authorization
      - loki
      - rabbitmq

  api:
    image: ca/api
    build:
      context: ../.
      dockerfile: src/CA.Api/Dockerfile
    depends_on:
      - identity
      - authorization
      - loki
      - rabbitmq

  bff:
    image: ca/bff
    build:
      context: ../.
      dockerfile: src/CA.BFF/Dockerfile
    depends_on:
      - identity
      - authorization
      - api
      - loki