version: '3.9'

services:
  identity-waf:
    environment:
      - BACKEND=http://identity
    ports:
      - "8090:80"
      - "8091:443"
    networks:
      - ca

  bff-waf:
    environment:
      - BACKEND=http://bff
    ports:
      - "8080:80"
      - "8081:443"
    networks:
      - ca

  identity:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - ClientUri=https://localhost:8081
    volumes:
      - identity-dpk:/root/.aspnet/DataProtection-Keys
    ports:
      - "80"
    networks:
      - ca
  
  authorization:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - TokenAuthority=https://identity
    ports:
      - "80"
    networks:
      - ca

  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - TokenAuthority=https://identity
      - AuthorizationService=http://authorization
    ports:
      - "80"
    networks:
      - ca

  bff:
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ASPNETCORE_URLS=http://+:80
      - TokenAuthority=https://identity
      - Clusters__apicluster__Destinations__api1__Address=http://api
    volumes:
      - bff-dpk:/root/.aspnet/DataProtection-Keys
    ports:
      - "80"
    networks:
      - ca

networks:
  ca:

volumes:
  identity-dpk:
  bff-dpk: